### ISSUE TITLE
Support `@...` syntax

### ISSUE THREAD

**Issue by Aerijo** [hesstobi/atom-autocomplete-latex-cite#6]
I think it would be really neat if your citation provider could activate following a `@`, much like referencing people in markdown. If you were to include this as an optional feature, it should not cause any harm to those who just disable it.

Having said that, it would probably take ~~some~~ a lot of effort. I'm willing to help out where I can, but I'm not too familiar with coffeescript. I've already implemented a basic version in my [`autocomplete-latex`](https://github.com/Aerijo/autocomplete-latex) package, but it lacks the power of your parsing of the `.bib` file and formatting the resulting completions. Currently, when the prefix is detected to start with an `@`, it looks for a path to the `.bib` file. If found, it takes the valid labels and presents them in the autocomplete popup. Choosing one replaces something like `@1.1` with `\parencite{1.1}`, or whatever citation command the user sets.

Maybe your completions functions can be bundled up and exposed as a provider? This way, I could consume it and give it the prefix, and it would return the correct completions. You also wouldn't have to worry about replacing the `@` with the correct cite command, as I would do that on my end.

I understand if you feel this isn't worth the effort. I think that being able to make things like this is part of what makes Atom good though. And if you don't have any time to spare, I'll give my best shot at it and make a PR :)

**Comment by hesstobi** [comment]
I think the package should not activate following a '@'. Because this is not a valid latex syntax. And thus with the current implementation of this package it is not possible to use the prefix. Because the package is limited to the scope '.meta.citation.latex'.

But you are right the package should be divided in an autocomplete provider and the bib-resource provider interacting with the service API. This would allow providing citation for different languages and other resources. I will think about this.

To get the behavior you propose, it is possible to create a snippet for '@' which expands e.g. to '\parencite{$1}'. After that this package should work as expected.

Or you use the [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package which is written for markdown, but can also be used with latex. But I wrote this package because [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) only supports system wide bib file resources and also does not work well with other autocomplete packages. I also want the autocompletion is working for all citation command in latex.
